#!/bin/bash

# parameters
PBF=http://download.geofabrik.de/osm/europe/andorra.osm.pbf
OSM=http://download.geofabrik.de/osm/europe/andorra.osm.bz2
USER=openstreetmap
DATABASE=test
PASSWORD=dfkiteam
PSQL_VERSION=8.4
MODE=development #development, test or productive
RAILS_PORT_FOLDER=$HOME/web/rails-port 
PLANNING_DO_ROAM=$HOME/web/planning-do-roam/ActivityRoutePlanner

# trace, and stop if there are errors
set -e
set -x

OSM_FILE=$(basename $OSM)

# 1. set up the OSM database and give the user "$USER" all privileges 

psql -U $USER -c "DROP DATABASE $DATABASE;" || true
createdb -U $USER $DATABASE
createlang -U $USER plpgsql $DATABASE
echo "Here you need to be postgres, the PostgreSQL-Admin"
psql -U postgres -d $DATABASE < /usr/share/postgresql/$PSQL_VERSION/contrib/btree_gist.sql
psql -U $USER -d $DATABASE -c "GRANT ALL PRIVILEGES ON DATABASE $DATABASE TO $USER" 

# 2. create the OSM tables

# in the rails port repository folder
cd $RAILS_PORT_FOLDER
cp config/database.yml config/database.yml.original
echo "
#DO-ROAM-DB-Setup
development:
  adapter: postgresql
  database: $DATABASE
  username: openstreetmap
  password: dfkiteam
  host: localhost
  port: 5432
  encoding: utf8" > config/database.yml
rake db:migrate RAILS_ENV=development
mv -f config/database.yml.original config/database.yml

# 3. run Osmosis

# first drop indexes that cause problems
psql -U postgres -d $DATABASE -c "DROP INDEX users_display_name_idx;"
psql -U postgres -d $DATABASE -c "DROP INDEX users_email_idx;"

cd $PLANNING_DO_ROAM
rm $OSM_FILE || true
wget $OSM 

bzcat $OSM_FILE | osmosis --fast-read-xml-0.6 file=/dev/stdin --write-apidb-0.6 populateCurrentTables=yes host="localhost" database="$DATABASE" user="$USER" password="$PASSWORD" validateSchemaVersion=no 

# 5. in the planning repository folder run

rake db:migrate RAILS_ENV=$MODE
rake ontology:read RAILS_ENV=$MODE
rake intervals:read RAILS_ENV=$MODE

