#!/bin/bash

# parameters
PBF=http://download.geofabrik.de/openstreetmap/europe/germany/bremen.osm.pbf
OSM=http://download.geofabrik.de/openstreetmap/europe/germany/bremen.osm.bz2
USER=openstreetmap
DATABASE=bremen
PASSWORD=dfkiteam
PSQL_VERSION=9.1
MODE=development #development, test or productive
RAILS_PORT_FOLDER=$HOME/doroam/rails-port 
PLANNING_DO_ROAM=$HOME/doroam/planning-do-roam
OSMOSIS=$HOME/doroam/osmosis-0.41/bin/osmosis

# trace, and stop if there are errors
set -e
set -x

sudo apt-get install 

OSM_FILE=$(basename $OSM)

# 0 make rails project ready
bundle install

# 1. set up the OSM database and give the user "$USER" all privileges 

psql -U openstreetmap postgres -c "DROP DATABASE $DATABASE;" || true
createdb -U $USER $DATABASE
createlang -U $USER plpgsql $DATABASE || true
if [ $PSQL_VERSION == 9.1 ]; then
  psql -U openstreetmap -d $DATABASE -c "CREATE EXTENSION btree_gist;"
else
  echo "Here you need to be postgres, the PostgreSQL-Admin"
  psql -U openstreetmap -d DATABASE < /usr/share/postgresql/$PSQL_VERSION/contrib/btree_gist.sql
fi
psql -U $USER -d $DATABASE -c "GRANT ALL PRIVILEGES ON DATABASE $DATABASE TO $USER" 

# 2. create the OSM tables

# in the rails port repository folder
cd $RAILS_PORT_FOLDER
mv config/database.yml config/database.yml.original || true
echo "
#DO-ROAM-DB-Setup
development:
  adapter: postgresql
  database: $DATABASE
  username: openstreetmap
  password: dfkiteam
  host: localhost
  port: 5432
  encoding: utf8" > config/database.yml
bundle install
bundle exec rake db:migrate RAILS_ENV=development || true
mv -f config/database.yml.original config/database.yml || true

# 3. run Osmosis

# first drop indexes that cause problems
psql -U openstreetmap -d $DATABASE -c "DROP INDEX users_display_name_idx;"
psql -U openstreetmap -d $DATABASE -c "DROP INDEX users_email_idx;"

cd $PLANNING_DO_ROAM
rm $OSM_FILE || true
wget $OSM 

bzcat $OSM_FILE | $OSMOSIS --fast-read-xml-0.6 file=/dev/stdin --write-apidb-0.6 populateCurrentTables=yes host="localhost" database="$DATABASE" user="$USER" password="$PASSWORD" validateSchemaVersion=no 

# 5. in the planning repository folder run

rake db:migrate RAILS_ENV=$MODE
rake ontology:read RAILS_ENV=$MODE
rake intervals:read RAILS_ENV=$MODE

