ALTER TABLE casedwords DROP CONSTRAINT fk_casedwords_wordid CASCADE;
ALTER TABLE synsets DROP CONSTRAINT fk_synsets_lexdomainid CASCADE;
ALTER TABLE samples DROP CONSTRAINT fk_samples_synsetid CASCADE;
ALTER TABLE senses DROP CONSTRAINT fk_senses_wordid CASCADE;
ALTER TABLE senses DROP CONSTRAINT fk_senses_synsetid CASCADE;
ALTER TABLE semlinks DROP CONSTRAINT fk_semlinks_synset1id CASCADE;
ALTER TABLE semlinks DROP CONSTRAINT fk_semlinks_synset2id CASCADE;
ALTER TABLE semlinks DROP CONSTRAINT fk_semlinks_linkid CASCADE;
ALTER TABLE lexlinks DROP CONSTRAINT fk_lexlinks_synset1id CASCADE;
ALTER TABLE lexlinks DROP CONSTRAINT fk_lexlinks_synset2id CASCADE;
ALTER TABLE lexlinks DROP CONSTRAINT fk_lexlinks_word1id CASCADE;
ALTER TABLE lexlinks DROP CONSTRAINT fk_lexlinks_word2id CASCADE;
ALTER TABLE lexlinks DROP CONSTRAINT fk_lexlinks_linkid CASCADE;
ALTER TABLE morphmaps DROP CONSTRAINT fk_morphmaps_wordid CASCADE;
ALTER TABLE morphmaps DROP CONSTRAINT fk_morphmaps_morphid CASCADE;
ALTER TABLE vframemaps DROP CONSTRAINT fk_vframemaps_frameid CASCADE;
ALTER TABLE vframemaps DROP CONSTRAINT fk_vframemaps_synsetid CASCADE;
ALTER TABLE vframemaps DROP CONSTRAINT fk_vframemaps_wordid CASCADE;
ALTER TABLE vframesentencemaps DROP CONSTRAINT fk_vframesentencemaps_sentenceid CASCADE;
ALTER TABLE vframesentencemaps DROP CONSTRAINT fk_vframesentencemaps_synsetid CASCADE;
ALTER TABLE vframesentencemaps DROP CONSTRAINT fk_vframesentencemaps_wordid CASCADE;
ALTER TABLE adjpositions DROP CONSTRAINT fk_adjpositions_synsetid CASCADE;
ALTER TABLE adjpositions DROP CONSTRAINT fk_adjpositions_wordid CASCADE;
DROP INDEX k_casedwords_wordid;
DROP INDEX k_synsets_lexdomainid;
DROP INDEX k_samples_synsetid;
DROP INDEX k_senses_wordid;
DROP INDEX k_senses_synsetid;
DROP INDEX k_semlinks_synset1id;
DROP INDEX k_semlinks_synset2id;
DROP INDEX k_semlinks_linkid;
DROP INDEX k_lexlinks_synset1id_word1id;
DROP INDEX k_lexlinks_synset2id_word2id;
DROP INDEX k_lexlinks_linkid;
DROP INDEX k_lexlinks_synset1id;
DROP INDEX k_lexlinks_word1id;
DROP INDEX k_lexlinks_synset2id;
DROP INDEX k_lexlinks_word2id;
DROP INDEX k_morphmaps_wordid;
DROP INDEX k_morphmaps_morphid;
DROP INDEX k_vframemaps_frameid;
DROP INDEX k_vframemaps_synsetid;
DROP INDEX k_vframemaps_wordid;
DROP INDEX k_vframesentencemaps_sentenceid;
DROP INDEX k_vframesentencemaps_synsetid;
DROP INDEX k_vframesentencemaps_wordid;
DROP INDEX k_adjpositions_synsetid;
DROP INDEX k_adjpositions_wordid;
DROP INDEX unq_words_lemma;
DROP INDEX unq_casedwords_cased;
DROP INDEX unq_senses_senseid;
DROP INDEX unq_senses_sensekey;
DROP INDEX unq_morphs_morph;
ALTER TABLE words DROP CONSTRAINT pk_words CASCADE;
ALTER TABLE casedwords DROP CONSTRAINT pk_casedwords CASCADE;
ALTER TABLE synsets DROP CONSTRAINT pk_synsets CASCADE;
ALTER TABLE postypes DROP CONSTRAINT pk_postypes CASCADE;
ALTER TABLE lexdomains DROP CONSTRAINT pk_lexdomains CASCADE;
ALTER TABLE samples DROP CONSTRAINT pk_samples CASCADE;
ALTER TABLE senses DROP CONSTRAINT pk_senses CASCADE;
ALTER TABLE linktypes DROP CONSTRAINT pk_linktypes CASCADE;
ALTER TABLE semlinks DROP CONSTRAINT pk_semlinks CASCADE;
ALTER TABLE lexlinks DROP CONSTRAINT pk_lexlinks CASCADE;
ALTER TABLE morphs DROP CONSTRAINT pk_morphs CASCADE;
ALTER TABLE morphmaps DROP CONSTRAINT pk_morphmaps CASCADE;
ALTER TABLE vframes DROP CONSTRAINT pk_vframes CASCADE;
ALTER TABLE vframemaps DROP CONSTRAINT pk_vframemaps CASCADE;
ALTER TABLE vframesentences DROP CONSTRAINT pk_vframesentences CASCADE;
ALTER TABLE vframesentencemaps DROP CONSTRAINT pk_vframesentencemaps CASCADE;
ALTER TABLE adjpositiontypes DROP CONSTRAINT pk_adjpositiontypes CASCADE;
ALTER TABLE adjpositions DROP CONSTRAINT pk_adjpositions CASCADE;

ALTER TABLE words ADD CONSTRAINT pk_words PRIMARY KEY (wordid);
ALTER TABLE casedwords ADD CONSTRAINT pk_casedwords PRIMARY KEY (casedwordid);
ALTER TABLE synsets ADD CONSTRAINT pk_synsets PRIMARY KEY (synsetid);
ALTER TABLE postypes ADD CONSTRAINT pk_postypes PRIMARY KEY (pos);
ALTER TABLE lexdomains ADD CONSTRAINT pk_lexdomains PRIMARY KEY (lexdomainid);
ALTER TABLE samples ADD CONSTRAINT pk_samples PRIMARY KEY (synsetid,sampleid);
ALTER TABLE senses ADD CONSTRAINT pk_senses PRIMARY KEY (wordid,synsetid);
ALTER TABLE linktypes ADD CONSTRAINT pk_linktypes PRIMARY KEY (linkid);
ALTER TABLE semlinks ADD CONSTRAINT pk_semlinks PRIMARY KEY (synset1id,synset2id,linkid);
ALTER TABLE lexlinks ADD CONSTRAINT pk_lexlinks PRIMARY KEY (word1id,synset1id,word2id,synset2id,linkid);
ALTER TABLE morphs ADD CONSTRAINT pk_morphs PRIMARY KEY (morphid);
ALTER TABLE morphmaps ADD CONSTRAINT pk_morphmaps PRIMARY KEY(morphid,pos,wordid);
ALTER TABLE vframes ADD CONSTRAINT pk_vframes PRIMARY KEY (frameid);
ALTER TABLE vframemaps ADD CONSTRAINT pk_vframemaps PRIMARY KEY (synsetid,wordid,frameid);
ALTER TABLE vframesentences ADD CONSTRAINT pk_vframesentences PRIMARY KEY(sentenceid);
ALTER TABLE vframesentencemaps ADD CONSTRAINT pk_vframesentencemaps PRIMARY KEY (synsetid,wordid,sentenceid);
ALTER TABLE adjpositiontypes ADD CONSTRAINT pk_adjpositiontypes PRIMARY KEY (position);
ALTER TABLE adjpositions ADD CONSTRAINT pk_adjpositions PRIMARY KEY (synsetid,wordid);
CREATE UNIQUE INDEX unq_words_lemma ON words (lemma);
CREATE UNIQUE INDEX unq_casedwords_cased ON casedwords (cased);
CREATE UNIQUE INDEX unq_senses_senseid ON senses (senseid);
CREATE UNIQUE INDEX unq_senses_sensekey ON senses (sensekey);
CREATE UNIQUE INDEX unq_morphs_morph ON morphs (morph);
CREATE INDEX k_casedwords_wordid ON casedwords (wordid);
CREATE INDEX k_synsets_lexdomainid ON synsets (lexdomainid);
CREATE INDEX k_samples_synsetid ON samples (synsetid);
CREATE INDEX k_senses_synsetid ON senses (synsetid);
CREATE INDEX k_senses_wordid ON senses (wordid);
CREATE INDEX k_semlinks_linkid ON semlinks (linkid);
CREATE INDEX k_semlinks_synset1id ON semlinks (synset1id);
CREATE INDEX k_semlinks_synset2id ON semlinks (synset2id);
CREATE INDEX k_lexlinks_linkid ON lexlinks (linkid);
CREATE INDEX k_lexlinks_synset1id ON lexlinks (synset1id);
CREATE INDEX k_lexlinks_synset1id_word1id ON lexlinks (synset1id,word1id);
CREATE INDEX k_lexlinks_synset2id ON lexlinks (synset2id);
CREATE INDEX k_lexlinks_synset2id_word2id ON lexlinks (synset2id,word2id);
CREATE INDEX k_lexlinks_word1id ON lexlinks (word1id);
CREATE INDEX k_lexlinks_word2id ON lexlinks (word2id);
CREATE INDEX k_morphmaps_morphid ON morphmaps (morphid);
CREATE INDEX k_morphmaps_wordid ON morphmaps (wordid);
CREATE INDEX k_vframemaps_frameid ON vframemaps (frameid);
CREATE INDEX k_vframemaps_synsetid ON vframemaps (synsetid);
CREATE INDEX k_vframemaps_wordid ON vframemaps (wordid);
CREATE INDEX k_vframesentencemaps_sentenceid ON vframesentencemaps (sentenceid);
CREATE INDEX k_vframesentencemaps_synsetid ON vframesentencemaps (synsetid);
CREATE INDEX k_vframesentencemaps_wordid ON vframesentencemaps (wordid);
CREATE INDEX k_adjpositions_synsetid ON adjpositions (synsetid);
CREATE INDEX k_adjpositions_wordid ON adjpositions (wordid);
ALTER TABLE casedwords ADD CONSTRAINT fk_casedwords_wordid FOREIGN KEY (wordid) REFERENCES words(wordid);
ALTER TABLE synsets ADD CONSTRAINT fk_synsets_lexdomainid FOREIGN KEY (lexdomainid) REFERENCES lexdomains (lexdomainid);
ALTER TABLE samples ADD CONSTRAINT fk_samples_synsetid FOREIGN KEY (synsetid) REFERENCES synsets(synsetid);
ALTER TABLE senses ADD CONSTRAINT fk_senses_synsetid FOREIGN KEY (synsetid) REFERENCES synsets(synsetid);
ALTER TABLE senses ADD CONSTRAINT fk_senses_wordid FOREIGN KEY (wordid) REFERENCES words(wordid);
ALTER TABLE semlinks ADD CONSTRAINT fk_semlinks_linkid FOREIGN KEY (linkid) REFERENCES linktypes (linkid);
ALTER TABLE semlinks ADD CONSTRAINT fk_semlinks_synset1id FOREIGN KEY (synset1id) REFERENCES synsets (synsetid);
ALTER TABLE semlinks ADD CONSTRAINT fk_semlinks_synset2id FOREIGN KEY (synset2id) REFERENCES synsets (synsetid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_linkid FOREIGN KEY (linkid) REFERENCES linktypes (linkid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_synset1id FOREIGN KEY (synset1id) REFERENCES synsets (synsetid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_synset2id FOREIGN KEY (synset2id) REFERENCES synsets (synsetid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_word1id FOREIGN KEY (word1id) REFERENCES words (wordid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_word2id FOREIGN KEY (word2id) REFERENCES words (wordid);
ALTER TABLE morphmaps ADD CONSTRAINT fk_morphmaps_morphid FOREIGN KEY (morphid) REFERENCES morphs(morphid);
ALTER TABLE morphmaps ADD CONSTRAINT fk_morphmaps_wordid FOREIGN KEY (wordid) REFERENCES words(wordid);
ALTER TABLE vframemaps ADD CONSTRAINT fk_vframemaps_frameid FOREIGN KEY (frameid) REFERENCES vframes(frameid);
ALTER TABLE vframemaps ADD CONSTRAINT fk_vframemaps_synsetid FOREIGN KEY (synsetid) REFERENCES synsets(synsetid);
ALTER TABLE vframemaps ADD CONSTRAINT fk_vframemaps_wordid FOREIGN KEY (wordid) REFERENCES words(wordid);
ALTER TABLE vframesentencemaps ADD CONSTRAINT fk_vframesentencemaps_sentenceid FOREIGN KEY (sentenceid) REFERENCES vframesentences(sentenceid);
ALTER TABLE vframesentencemaps ADD CONSTRAINT fk_vframesentencemaps_synsetid FOREIGN KEY (synsetid) REFERENCES synsets(synsetid);
ALTER TABLE vframesentencemaps ADD CONSTRAINT fk_vframesentencemaps_wordid FOREIGN KEY (wordid) REFERENCES words(wordid);
ALTER TABLE adjpositions ADD CONSTRAINT fk_adjpositions_synsetid FOREIGN KEY (synsetid) REFERENCES synsets (synsetid);
ALTER TABLE adjpositions ADD CONSTRAINT fk_adjpositions_wordid FOREIGN KEY (wordid) REFERENCES words (wordid);
